
<body>
<br><br><br><br>
<!-- Main jumbotron for a primary marketing message or call to action -->
<input id="city_id" type="hidden" value="<?php echo $this->city['city_id']; ?>">
<div class="jumbotron">
	<div class="container">
		<h1><?php echo $this->city['city_name']; ?></h1>
		<pre><?php echo $this->city['description'] ?></pre>
		<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
	</div>
</div>

<div class="container">
	<div class="container">
		<?php

		$user_model_object = new Application_Model_User();

		$exp_index = 0;
		for($i=0;$i< ceil(count($this->experiences)/3);$i++){
			echo '<div class="row stylish-panel">';
			for($exp_index;$exp_index < count($this->experiences);$exp_index++){

				$user_name = json_decode($user_model_object->getUsername($this->experiences[$exp_index]['user_id']),true);

				echo '<div class="col-md-4">
							<div>
								<h2>'.$user_name['user_name'].'</h2>
								<p>'.$this->experiences[$exp_index]['post_title'].'</p>
								<a href="/userexp/view/eid/'.$this->experiences[$exp_index]['post_id'].'" class="btn btn-default" title="See more">See Experience »</a>
							</div>
						</div>';
			}

			echo '</div>';
		}

		?>
	</div>
</div>
<!-- /container -->
<hr>
<div class="container">
	<div class="row">
		<div class="col-lg-offset-2 col-lg-8 col-lg-offset-2">
			<form method="post">
				<?php
				echo $this->UserExp_Form->getElement('post_title');
				echo '<br>';
				echo $this->UserExp_Form->getElement('post_desc');
				echo '<br>';
//				echo $this->UserExp_Form->getElement('ShareExperience');
//				echo '<br>';
				?>
				<button class="btn btn-success btn-lg" type="submit">Share Experience !!</button>
			</form>
		</div>
</div>
</div>
<hr>


<script src="/bootstrap/js/navbar.js"></script>
</body>

