<body class="homepage">
<section id="main-slider" class="no-margin">
    <div class="carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#main-slider" data-slide-to="0" class="active"></li>
            <li data-target="#main-slider" data-slide-to="1"></li>
            <li data-target="#main-slider" data-slide-to="2"></li>
            <li data-target="#main-slider" data-slide-to="3"></li>
            <li data-target="#main-slider" data-slide-to="4"></li>
            <li data-target="#main-slider" data-slide-to="5"></li>
        </ol>
        <div class="carousel-inner">

            <div class="item active" style="background-image: url(/bootstrap/images/slider/egy1.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
                                <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
                                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div><!--/.item-->

            <div class="item" style="background-image: url(/bootstrap/images/slider/italy.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
                                <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
                                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

            <div class="item" style="background-image: url(/bootstrap/images/slider/canada3.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
                                <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
                                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

            <div class="item" style="background-image: url(/bootstrap/images/slider/turkey.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
                                <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
                                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

            <div class="item" style="background-image: url(/bootstrap/images/slider/spain.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
                                <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
                                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

            <div class="item" style="background-image: url(/bootstrap/images/slider/moroco.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
                                <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
                                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
        </div><!--/.carousel-inner-->
    </div><!--/.carousel-->
    <a class="prev hidden-xs" href="#main-slider" data-slide="prev">
        <i class="fa fa-chevron-left"></i>
    </a>
    <a class="next hidden-xs" href="#main-slider" data-slide="next">
        <i class="fa fa-chevron-right"></i>
    </a>
</section><!--/#main-slider-->

<section id="top-6-cities">
    <div class="container">
        <div class="center wow fadeInDown">
            <h2>Top 6 Rated Cities</h2>
            <p class="lead"><h4>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</h4></p>
        </div>

        <div class="row wow fadeInDown">
            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="recent-work-wrap">
                    <img class="img-responsive" src="/bootstrap/images/top-6-cities/new_york_1%20(copy).jpg" alt="">
                    <div class="overlay">
                        <div class="recent-work-inner">
                            <h3><a href="#">New York</a> </h3>
                            <a class="preview" href="/bootstrap/images/top-6-cities/new_york_1%20(copy).jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="recent-work-wrap">
                    <img class="img-responsive" src="/bootstrap/images/top-6-cities/Alexandria-102%20(copy).jpg" alt="">
                    <div class="overlay">
                        <div class="recent-work-inner">
                            <h3><a href="#">Alexandria</a></h3>
                            <a class="preview" href="/bootstrap/images/top-6-cities/Alexandria-102%20(copy).jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="recent-work-wrap">
                    <img class="img-responsive" src="/bootstrap/images/top-6-cities/LuxorTemple1%20(copy).jpg" alt="">
                    <div class="overlay">
                        <div class="recent-work-inner">
                            <h3><a href="#">Luxor </a></h3>
                            <a class="preview" href="/bootstrap/images/top-6-cities/LuxorTemple1%20(copy).jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="recent-work-wrap">
                    <img class="img-responsive" src="/bootstrap/images/top-6-cities/rome.jpg" alt="">
                    <div class="overlay">
                        <div class="recent-work-inner">
                            <h3><a href="#">Rome </a></h3>
                            <a class="preview" href="/bootstrap/images/top-6-cities/rome.jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="recent-work-wrap">
                    <img class="img-responsive" src="/bootstrap/images/top-6-cities/istanbul%20(copy).jpg" alt="">
                    <div class="overlay">
                        <div class="recent-work-inner">
                            <h3><a href="#">Istanbul</a></h3>
                            <a class="preview" href="/bootstrap/images/top-6-cities/istanbul%20(copy).jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="recent-work-wrap">
                    <img class="img-responsive" src="/bootstrap/images/top-6-cities/sydney_harbour%20(copy).jpg" alt="">
                    <div class="overlay">
                        <div class="recent-work-inner">
                            <h3><a href="#">Sydney </a></h3>
                            <a class="preview" href="/bootstrap/images/top-6-cities/sydney_harbour.jpg" rel="prettyPhoto"><i class="fa fa-eye"></i> View</a>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/.row-->
    </div><!--/.container-->
</section><!--/#top-6-rated-cities-->

<footer id="footer" class="midnight-blue">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                &copy; 2016 <a target="_blank" href="index.html">SaFaRnY.com</a>. All Rights Reserved.
            </div>
            <div class="col-sm-6">
                <ul class="pull-right">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer><!--/#footer-->

<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/bootstrap/js/jquery.prettyPhoto.js"></script>
<script src="/bootstrap/js/jquery.isotope.min.js"></script>
<script src="/bootstrap/js/main.js"></script>
<script src="/bootstrap/js/wow.min.js"></script>
</body>
</html>