<style>
.color{

	color:black;
	
}
.errors{
	color:red;
}

</style>
<body style="background-image: url('/bootstrap/images/countries/luxor.jpeg')">

<div id="view-content">
<div class="container " style="border-style: solid;margin-top: 150px;border-color: #E6E6FA;width:750px;    left: 50%;background-color:#F0FFF0;"   > <h2 >
<?php echo $this->hotel_form;?>
</h2>
<h2 style="color:red">List of all hotels </h2>

<div class="table-responsive" >

	<table class="table table-striped table-bordered table-hover table-sm info text-info ">
		<thead class="thead-default">
						<th>hotel</th><th>city</th><th></th></thead>
	<?php

		$i=0;
		foreach($this->hotels as $key => $value)
			{
				echo "<tr>".

				"<td>" . $value["hotel_name"] . "</td>" .
									
				"<td>" . $this->city[$i]['city_name']. "</td> 
				<td> <a class='btn btn-info' href='delete/hid/".$value['hotel_id']."' > Edit </a>  <a class='btn btn-danger' href='delete/hid/".$value['hotel_id']."' > Delete </a></td> 

				</tr>";
				$i=$i+1;
									}
			?>

	</table>
</div></div></div>
</body>