<div style="margin-top: 150px;"></div>

<div class="container">
    <h2  align="center"  style="color:blue; font-size: 4em;">Car Rental</h2>
    <div class="row">
        <div class="col-lg-offset-4 col-lg-4">
            <form method="post" action="">

                <input type="hidden" name="city_id" value="<?php echo $this->city_id ; ?>">
                <?php
                echo $this->car_form->getElement('pickup_location');
                echo $this->car_form->getElement('date_from');
                echo $this->car_form->getElement('date_to');
                echo $this->car_form->getElement('GetYourQuote');

                ?>

            </form>
        </div>
    </div>

</div>



<link rel="stylesheet" href="/bootstrap/css/datepicker.css">
<script src="/bootstrap/js/bootstrap-datepicker.js"></script>
<script>
    $('#date_from').datepicker();
    $('#date_to').datepicker();
</script>
