<div style="margin-top: 150px;"></div>

<div class="container">
    <h2  align="center"  style="color:blue;"><font size="7">Car Rental</font></h2>
    <div class="row">
        <div class="col-lg-offset-4 col-lg-4">

            <?php echo $this->car_form;?>
        </div>

    </div>

</div>


<head>
<link rel="stylesheet" href="/datepicker.css">

<script src="/bootstrap-datepicker.js"></script>

    </head>
<script>
    $('#date_from').datepicker();


   $('#date_to').datepicker();



</script>
