<br /><br />
<div id="view-content">
	<p>View script for controller <b>UserData</b> and script/action name <b>carRental</b></p>
	<?php
		$authen_instance = Zend_Auth::getInstance();
        $storage = $authen_instance->getStorage();
        $sessionRead = $storage->read();
        if (!empty($sessionRead)) {
            $name = $sessionRead->user_name;
            echo "<br> <br> <br> <br><br>name:" . $name;
           // $object=(array) $sessionRead;
          // $object = array( $sessionRead);
           //$object= $object['user_name'];
          

           } ?>



           <a class="btn btn-default " href="<?php echo $this->baseUrl() ?>/user/edit-details"> Edit Profile</a>
</div>