<br /><br /><br><br /><br /><br>
<div id="view-content">

<div class="page-header" style="margin-top:150px;">
  <h1><?php echo $this->show_country_name[0]['country_name']; ?></h1>
</div>
<div>
<h3 style="text-size=45;"><?php echo $this->show_country_name[0]['country_description']; ?></h3>

</div>

<table class="table table-striped table-bordered table-hover info text-info ">


<?php
$i=0;
foreach($this->show_city_country as $key => $value)
{
echo "<tr>".

"<td>" . $value["city_name"] . "</td> 


</tr>";
$i=$i+1;}
?>
</table>
</div>