<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <p class="navbar-text" style="float:right;">
            <?php
            $auth = Zend_Auth::getInstance();
            $storage = $auth->getStorage();
            $sessionRead = $storage->read();
            $facebook_session = new Zend_Session_Namespace('facebook');

            if(!empty($sessionRead)) {
                $username = $sessionRead->user_name;

                echo "Welcome " . $username. " ";
                ?>
                <a class="btn btn-default navbar-btn" href="<?php echo $this->baseUrl() ?>/user/logout">Logout</a>

                <?php
            }elseif(isset($facebook_session->name)) {
                echo "Welcome " . $facebook_session->name . " ";

                ?>

                <a class="btn btn-default navbar-btn" href="<?php echo $this->baseUrl; ?>/user/fblogout"> Logout</a>
                <?php
            }
            ?>
        </p>

        <div class="navbar-header">
            <a class="navbar-brand" href="#">Zend-OpenSource</a>
        </div>
    </div>
</nav>

<?php echo $this->layout()->content; ?>

