<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | SaFaRanY.com</title>

    <!-- core CSS -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/bootstrap/css/font-awesome.min.css" rel="stylesheet">
    <link href="/bootstrap/css/animate.min.css" rel="stylesheet">
    <link href="/bootstrap/css/prettyPhoto.css" rel="stylesheet">
    <link href="/bootstrap/css/main.css" rel="stylesheet">
    <link href="/bootstrap/css/responsive.css" rel="stylesheet">
</head><!--/head-->

<?php
    $authen = Zend_Auth::getInstance();
    $storage = $authen->getStorage();
    $session_read = $storage->read();
    $facebook_session = new Zend_Session_Namespace('facebook');

    if(empty($session_read) && empty($facebook_session->name)){
        echo '<header id="header">
    <nav class="navbar navbar-inverse" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">SaFaRnY.com</a>
            </div>

            <div class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="index.html">Home</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Destinations <i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="">Egypt</a></li>
                            <li><a href="">Italy</a></li>
                            <li><a href="">Canada</a></li>
                            <li><a href="">Turkey</a></li>
                        </ul>
                    </li>
                    <li><a href="/user/login">Login</a></li>
                    <li><a href="#">SignUp</a></li>
                </ul>
            </div>
        </div><!--/.container-->
    </nav><!--/nav-->

</header><!--/header-->';
    }elseif(isset($facebook_session->name) && !empty($facebook_session->name)){

        echo '<header id="header">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">SaFaRnY.com</a>
            </div>

            <div class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="index.html">Home</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Destinations <i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="">Egypt</a></li>
                            <li><a href="">Italy</a></li>
                            <li><a href="">Canada</a></li>
                            <li><a href="">Turkey</a></li>
                        </ul>
                    </li>
                    <li>'."Welcome ".$facebook_session->name.' <a href="/user/fblogout">Logout</a></li>
                </ul>
            </div>
        </div><!--/.container-->
    </nav><!--/nav-->

</header><!--/header-->';

    }elseif(isset($session_read) && !empty($session_read)){

        $username = $session_read->user_name;
        echo '<header id="header">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">SaFaRnY.com</a>
            </div>

            <div class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="index.html">Home</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Destinations <i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="">Egypt</a></li>
                            <li><a href="">Italy</a></li>
                            <li><a href="">Canada</a></li>
                            <li><a href="">Turkey</a></li>
                        </ul>
                    </li>
                    <li>'."Welcome ".$username.' <a href="/user/logout">Logout</a></li>
                </ul>
            </div>
        </div><!--/.container-->
    </nav><!--/nav-->

</header><!--/header-->';
    }

?>


<?php echo $this->layout()->content; ?>