

<div class="container">
	<div style="height: 100px;"></div>
	<div class="row">

		<div class="col-md-6">
			<table class="table table-striped table-bordered table-hover">
				<thead>
				<tr>
					<th>Location Name</th>
					<th>Location Image</th>
					<th>Location's City</th>

				</tr>
				</thead>
				<tbody>
				<?php
				$i=0;
				foreach($this->locations as $key => $value)
				{
					echo "<tr>".
						 "<td>" . $value['location_name'] . "</td>" .
						 "<td>" . $value['location_image'] . "</td>" .
						 "<td>" . $this->cityname[$i]['city_name'] . "</td>" .
						 "<td> <a  class='btn btn-success' href='edit/lid/".$value['location_id']."'> Update </a>".
						 "<td> <a  class='btn btn-danger' href='delete/lid/".$value['location_id']."'> Delete </a>".
						 "</tr>";
					$i=$i+1;
				}
				?>


				</tbody>
			</table>
			<?php echo "<a  class='btn btn-info btn btn-block btn-lg' href='createlocation'> AddNewLocation </a>" ?>
		</div>

</div>
</div>



