

<div class="container">
	<div style="height: 150px;"></div>
	<div class="row">
		<div class="col-md-6">
			<table class="table table-striped table-bordered table-hover">
				<thead>
				<tr>
					<th>Location Name</th>
					<th>Location Image</th>
					<th>Location's City</th>

				</tr>
				</thead>
				<tbody>
				<?php
				$i=0;
				foreach($this->locations as $key => $value)
				{
					echo "<tr>".
						 "<td>" . $value['location_name'] . "</td>" .
						 "<td>" . $value['location_image'] . "</td>" .
						 "<td>" . $this->cityname[$i]['city_name'] . "</td>" .
						 "<td> <a  class='btn btn-success' href='createlocation/lid/".$value['location_id']."'> Update </a>".
						 "<td> <a  class='btn btn-warning' href='delete/lid/".$value['location_id']."'> Delete </a>".
						 "</tr>";
					$i=$i+1;
				}
				?>


				</tbody>
			</table>
		</div>
		<div class="col-lg-offset-4 col-lg-4">
			<?php

			echo $this->location_form;

			?>
	</div>
</div>
</div>
<div style="margin-top: 25px;"></div>

	<h2  align="center"  style="color:blue; font-size: 3em;">Add Location</h2>
	<div class="row">
		<div class="col-lg-offset-4 col-lg-4">
			<?php

			echo $this->location_form;

			?>
		</div>
	</div>


