<style>
	.color{
		color:black;
	}
	.errors{
		color:red;
	}

</style>

<body style="background-image: url('/bootstrap/images/countries/luxor.jpeg')">
<div id="view-content">


	<div class="container " style="border-style: solid;margin-top: 150px;border-color: #E6E6FA;width:500px;    left: 50%;background-color:#F0FFF0;"   >

		<?php echo $this->user_form;  ?>
		<?php echo $this->password_form; ?>

	</div>
</div>
</body>