<?php
    if(isset($this->errorMessage)){
        echo '<div class="container alert alert-danger alert-dismissible" role="alert">';
        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>';
        echo $this->errorMessage;
        echo '</div>';
    }
    ?>
</div>
<div class="container">
<?php
    echo $this->login_form;
?>

