<?php
    if(isset($this->errorMessage)){
        echo '<div class="container alert alert-danger alert-dismissible" role="alert">';
        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>';
        echo $this->errorMessage;
        echo '</div>';
    }
    ?>

<body style="background-image: url('/bootstrap/images/2.jpg')">
<br><br><br><br><br><br>
<div class="container">
    <div class="omb_login">
        <div class="row omb_row-sm-offset-3 omb_socialButtons">
            <div class="col-xs-4 col-sm-2">
                <?php echo '
                <a href="'.htmlspecialchars($this->facebook_url).'" class="btn btn-lg btn-block omb_btn-facebook"><i class="fa fa-facebook visible-xs"></i>
                    <span class="hidden-xs">Facebook</span>
                </a>';
                ?>
            </div>
            <div class="col-xs-4 col-sm-2">
                <a href="#" class="btn btn-lg btn-block omb_btn-twitter">
                    <i class="fa fa-twitter visible-xs"></i>
                    <span class="hidden-xs">Twitter</span>
                </a>
            </div>
            <div class="col-xs-4 col-sm-2">
                <a href="#" class="btn btn-lg btn-block omb_btn-google">
                    <i class="fa fa-google-plus visible-xs"></i>
                    <span class="hidden-xs">Google+</span>
                </a>
            </div>
        </div>

        <div class="row omb_row-sm-offset-3 omb_loginOr">
            <div class="col-xs-12 col-sm-6">
                <hr class="omb_hrOr">
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <form class="omb_loginForm" action="" method="POST">
                    <div class="input-group col-sm-12 col-sm-offset-0  col-lg-6 col-lg-offset-3">
                        <?php
                        echo $this->login_form->getElement('username');
                        ?>
                    </div>
                    <div class="input-group col-sm-12 col-sm-offset-0 col-lg-6 col-lg-offset-3">
                        <?php
                        echo $this->login_form->getElement('password');
                        ?>
                    </div>
                    <div class="input-group col-sm-12 col-sm-offset-0 col-lg-6 col-lg-offset-3">
                    <?php
                    echo $this->login_form->getElement('Login');
                    ?>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</body>