<?php
if(isset($this->errorMessage)){
	echo '<div class="container alert alert-danger alert-dismissible" role="alert">';
	echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>';
	echo $this->errorMessage;
	echo '</div>';
}
?>
</div>

<br>
<br>
<body style="background-image: url('/bootstrap/images/3.jpg')">
<div class="container">

	<div class="row">
		<div class="col-lg-offset-3 col-lg-6">
			<br><br>
			<form method="post">
				<?php
				echo $this->signUp_form->getElement('username');
				echo $this->signUp_form->getElement('email');
				echo $this->signUp_form->getElement('password');
				echo $this->signUp_form->getElement('c_password');
				echo $this->signUp_form->getElement('SignUp');
				?>
			</form>
		</div>
	</div>
</body>


