<style>
    body{
        background-size: cover;
    }
</style>
<body style="background-image: url('/bootstrap/images/car&hotel/hotels-4.jpg')">

<div class="container" style="margin-top: 100px">
    <div class="row">
        <div class="col-lg-offset-4 col-lg-4">

            <form method="post" action="">

                <input type="hidden" name="city_id" value="<?php echo $this->city_id ; ?>">
                <?php
                    echo $this->hotel_form->getElement('hotel_id');
                    echo $this->hotel_form->getElement('date_from');
                    echo $this->hotel_form->getElement('date_to');
                    echo $this->hotel_form->getElement('members');
                    echo $this->hotel_form->getElement('ReserveHotels');

                ?>

            </form>


        </div>

    </div>

</div>
</body>

<link rel="stylesheet" href="/bootstrap/css/datepicker.css">
<script src="/bootstrap/js/bootstrap-datepicker.js"></script>
<script>
    $('#date_from').datepicker();
    $('#date_to').datepicker();
   // $('#date_from').html("<span class='glyphicon glyphicon-ok form-control-feedback'></span>");
</script>
