<!-- Page Content -->
<div" class="container-fluid">

	<div class="row">

		<!-- Blog Post Content Column -->


		<div class="col-lg-offset-2 col-lg-8 col-lg-offset-2">

			<!-- Blog Post -->

			<!-- Title -->
			<h1>Blog Post Title</h1>

			<!-- Author -->
			<p class="lead">
				by <a href=" ">User Who Made the Experience</a>
			</p>

			<hr>

			<!-- Date/Time -->
			<p><span class="glyphicon glyphicon-time"></span> Date and Time of Experience</p>

			<hr>

			<!-- Preview Image -->
			<img class="img-responsive" src="http://placehold.it/900x300" alt="">

			<hr>

			<!-- Post Content -->
			<pre class="lead"><?php echo $this->experience['post']; ?></pre>

			<hr>

			<!-- Blog Comments -->

			<!-- Posted Comments -->

			<!-- Comment -->
			<h3>Comments: </h3>
			<div class="media">
				<a class="pull-left" href="#">
					<img class="media-object" src="http://placehold.it/64x64" alt="">
				</a>
				<div class="media-body">
					<h4 class="media-heading">Start Bootstrap
						<small>August 25, 2014 at 9:30 PM</small>
					</h4>
					Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
				</div>
			</div>

			<!-- Comment -->
			<div class="media">
				<a class="pull-left" href="#">
					<img class="media-object" src="http://placehold.it/64x64" alt="">
				</a>
				<div class="media-body">
					<h4 class="media-heading">Start Bootstrap
						<small>August 25, 2014 at 9:30 PM</small>
					</h4>
					Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
				</div>
			</div>
			<hr>
			<br>
			<!-- Comments Form -->
			<div class="well">
				<h4>Leave a Comment:</h4>
				<form role="form">
					<div class="form-group">
						<textarea class="form-control" rows="3"></textarea>
					</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>

			<hr>

		</div>